# Generated by Django 3.0.6 on 2020-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='date_resolved',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian'), ('Canteen Owner', 'Canteen Owner'), ('Vice-Principal', 'Vice-Principal'), ('Security Head', 'Security Head'), ('Principal', 'Principal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='branch',
            field=models.CharField(blank='true', choices=[('Computer', 'Computer'), ('IT', 'IT'), ('EXTC', 'EXTC'), ('ELEX', 'ELEX'), ('Chemical', 'Chemical'), ('Production', 'Production'), ('Bio Med', 'Bio Med')], max_length=300, null='true'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Management', 'Management'), ('Security', 'Security'), ('Library', 'Library'), ('Canteen', 'Canteen'), ('Faculty', 'Faculty')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed')], default='Pending', max_length=20),
        ),
    ]
