# Generated by Django 3.0.6 on 2020-06-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_auto_20200617_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='transfer',
            field=models.BooleanField(default='0'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Security Head', 'Security Head'), ('Canteen Owner', 'Canteen Owner'), ('Vice-Principal', 'Vice-Principal'), ('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Library', 'Library'), ('Management', 'Management'), ('Faculty', 'Faculty'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected'), ('Pending', 'Pending'), ('Solved', 'Solved')], default='Pending', max_length=20),
        ),
    ]
