# Generated by Django 3.0.3 on 2020-06-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0002_auto_20200619_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Canteen Owner', 'Canteen Owner'), ('Security Head', 'Security Head'), ('Senior Librarian', 'Senior Librarian'), ('Vice-Principal', 'Vice-Principal'), ('Principal', 'Principal'), ('HOD', 'HOD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Canteen', 'Canteen'), ('Management', 'Management'), ('Faculty', 'Faculty'), ('Security', 'Security'), ('Library', 'Library')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Viewed', 'Viewed'), ('Pending', 'Pending'), ('Solved', 'Solved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
