# Generated by Django 3.0.3 on 2020-06-20 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_auto_20200620_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Security Head', 'Security Head'), ('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('Canteen Owner', 'Canteen Owner')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Management', 'Management'), ('Library', 'Library'), ('Security', 'Security'), ('Faculty', 'Faculty'), ('Canteen', 'Canteen')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Viewed', 'Viewed'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='like',
            name='complain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='complain', to='grievance.Complain'),
        ),
    ]
