# Generated by Django 3.0.3 on 2020-06-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0003_auto_20200619_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='complain',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grievance.Complain'),
        ),
        migrations.AddField(
            model_name='like',
            name='liker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='grievance.Student'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head'), ('Principal', 'Principal'), ('Vice-Principal', 'Vice-Principal'), ('Canteen Owner', 'Canteen Owner')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Library', 'Library'), ('Faculty', 'Faculty'), ('Management', 'Management'), ('Canteen', 'Canteen'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved'), ('In Progress', 'In Progress'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
