# Generated by Django 3.0.3 on 2020-06-20 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grievance', '0004_auto_20200620_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='like_count',
        ),
        migrations.AddField(
            model_name='complain',
            name='likes',
            field=models.ManyToManyField(related_name='complain', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head'), ('Vice-Principal', 'Vice-Principal'), ('HOD', 'HOD')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Management', 'Management'), ('Security', 'Security')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('In Progress', 'In Progress'), ('Viewed', 'Viewed'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
