# Generated by Django 3.0.6 on 2020-06-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0004_auto_20200519_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Canteen Owner', 'Canteen Owner'), ('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head'), ('Vice-Principal', 'Vice-Principal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Rejected', 'Rejected'), ('Viewed', 'Viewed')], default='Pending', max_length=20),
        ),
    ]
