# Generated by Django 3.0.6 on 2020-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0005_auto_20200616_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='date_resolved',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Security Head', 'Security Head'), ('Vice-Principal', 'Vice-Principal'), ('Senior Librarian', 'Senior Librarian'), ('HOD', 'HOD'), ('Canteen Owner', 'Canteen Owner')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Security', 'Security'), ('Management', 'Management'), ('Canteen', 'Canteen'), ('Library', 'Library'), ('Faculty', 'Faculty')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Solved', 'Solved'), ('Pending', 'Pending'), ('Viewed', 'Viewed'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
