# Generated by Django 3.0.6 on 2020-06-17 01:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0006_auto_20200617_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Vice-Principal', 'Vice-Principal'), ('Principal', 'Principal'), ('Security Head', 'Security Head'), ('HOD', 'HOD'), ('Canteen Owner', 'Canteen Owner'), ('Senior Librarian', 'Senior Librarian')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_resolved',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Faculty', 'Faculty'), ('Management', 'Management'), ('Library', 'Library'), ('Security', 'Security'), ('Canteen', 'Canteen')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved'), ('Viewed', 'Viewed')], default='Pending', max_length=20),
        ),
    ]
