# Generated by Django 3.0.6 on 2020-06-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0008_auto_20200617_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='designation',
            field=models.CharField(choices=[('Vice-Principal', 'Vice-Principal'), ('Canteen Owner', 'Canteen Owner'), ('Principal', 'Principal'), ('HOD', 'HOD'), ('Senior Librarian', 'Senior Librarian'), ('Security Head', 'Security Head')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_resolved',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='complain',
            name='related_to',
            field=models.CharField(choices=[('Management', 'Management'), ('Library', 'Library'), ('Faculty', 'Faculty'), ('Security', 'Security'), ('Canteen', 'Canteen')], default='', max_length=20, verbose_name='Complain Related to'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Viewed', 'Viewed'), ('Solved', 'Solved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress')], default='Pending', max_length=20),
        ),
    ]
